### ISSUE TITLE
Error when deleting a charge

### ISSUE THREAD

**Issue by DavidVII** [nsweeting/shopify#24]
Hello, I got an error when deleting a charge. It appears that the request to cancel works, but the `parse_json/2` function in the `Response` module throws an error.

```
Shopify.RecurringApplicationCharge.delete(session, 1234)
> no case clause matching: {:error, :invalid, 0}
    (shopify) lib/shopify/response.ex:24: Shopify.Response.parse_json/2
    (shopify) lib/shopify/response.ex:12: Shopify.Response.new/3
```

It appears that `parse_json` is being called with the following arguments: `parse_json(nil, "")`

`nil` being the resource, and `""` is the body.

This results in the following being called [here](https://github.com/nsweeting/shopify/blob/77fd3aaec782c3350b5c001f89fb8bf12137c919/lib/shopify/response.ex#L24):

```
Poison.decode("", as: nil)
> {:error, :invalid, 0}
```

You'll notice the result there is the same as my error above. I'm happy to take a stab at a PR for this, but I'm curious how we might want to handle the response here?

There's no response body from Shopify according to [their docs](https://help.shopify.com/api/reference/recurringapplicationcharge#destroy). This seems inconsistent with other DELETE calls where the response body is an empty JSON object.

**Comment by Ninigi** [comment]
The API is full of inconsistencies, so I am not really surprised ;)
I guess we could just pattern match here and replace empty strings with an empty json object.
