### ISSUE TITLE
All resource calls return 401 for private app

### ISSUE THREAD

**Issue by johnmosesman** [nsweeting/shopify#31]
I'm hoping I just missed something obvious, but I can't get these two simple calls to return our data.

```
Shopify.session("my-shop-name", "my-api-key", "my-password")
|> Shopify.Product.all
{:error, %Shopify.Response{code: 401, data: nil}}
```

I've double-checked the API key and password are correct, and I've used both `shop-name` and `shop-name.myshopify.com`. 

I am able to curl the example URL generated in the private app settings using the format `https://apikey:password@hostname/admin/resource.json`. 

Any ideas?

**Comment by nsweeting** [comment]
Hi @johnmosesman

There has been a recent version bump on hex. I haven't confirmed it, but the old hex version may not have worked. In your deps, please use:

```
{:shopify, "~> 0.2.0"}
```

```
session = Shopify.session("my-shop-name.myshopify.com", "my-api-key", "my-password")
Shopify.Product.all(session)
# results returned
```

I just tested using a private app locally and everything worked.

Barring that, I would suggest checking the permissions for that api key + password are setup for read access on products.

**Comment by johnmosesman** [comment]
haha! Must have been mere minutes after I checked hex initially for the version number. 0.2 works great. 

Thanks for the quick reply!
