### ISSUE TITLE
Set timeout for HTTPoison requests

### ISSUE THREAD

**Issue by vladimir-e** [nsweeting/shopify#39]
Now when I fixed #38 in my fork, I notice that I get too much `:timeouts` from `HTTPoison`. The default `: recv_timeout` in HTTPoison is 5000ms. That's enough for most of requests, but when I create a product with multiple images, shopify just unable to download all images in such a short time (might be due to a slow third-party server that host images).

The lib already has a handy struct that we passing around - `session`. Do you think we could add httpoison_options that will override `@options` in HTTP adapter:

``` elixir
defmodule Shopify.Adapters.HTTP do
  @moduledoc false

  @behaviour Shopify.Adapters.Base
  @options [hackney: [pool: :shopify], ssl: [{:versions, [:"tlsv1.2"]}]]

  def get(request) do
    HTTPoison.get(request.full_url, request.headers, @options)
    |> handle_response(request.resource)
  end
  # ...
```

Example usage could be:

``` elixir
session_longer_timeout = session |> Map.put(:httpoison, %{recv_timeout: 15000})
Shopify.Product.create(session_longer_timeout, product_with_lots_of_images)
```

**Comment by nsweeting** [comment]
I added the potential for request options via #44 

```elixir
session_longer_timeout = session |> Shopify.Session.put_req_opt(:recv_timeout, 15_000)
Shopify.Product.create(session_longer_timeout, product_with_lots_of_images)
```

```elixir
session_longer_timeout = session |> Shopify.Session.put_req_opts([timeout: 15_000, recv_timeout: 15_000)
Shopify.Product.create(session_longer_timeout, product_with_lots_of_images)
```

@vladimir-e Work for you?

**Comment by vladimir-e** [comment]
Huge thanks @nsweeting ! Now I can stop using my fork (haven't got to making proper PR for it).

I reproduced the problem that #44 solves in my project like:

```
Shopify.session(name, access_token)
    |> Shopify.Session.put_req_opt(:recv_timeout, 500)
```

And then verified that it gets fixed with:

```
Shopify.session(name, access_token)
    |> Shopify.Session.put_req_opt(:recv_timeout, 30_000)
```

Looks good 👍
