### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by panoply** [nsweeting/shopify#40]
Thanks to all contributors for all your work on this project. It would be great to get some more detailed information regarding the installation, authentication process and recurring billing for public app usage with this package. Thanks again.

**Comment by Ninigi** [comment]
Hi @panoply 
I think you are right, the Shopify package alone is a little hard to use if you do not already know how to build a Shopify app without their official gem in Ruby. I will start writing an example and document the steps.

Thanks for your feedback!

**Comment by panoply** [comment]
Hey @Ninigi  I think the main thing to cover is the HMAC verification for Public Apps. While establishing the connection via OAUTH works perfectly, ensuring a request come from shopify within Embedded apps seems to be a little more difficult, as per Shopify docs [here](https://help.shopify.com/api/getting-started/authentication/oauth#verification).  Currently I'm using [uberauth_shopify](https://hexdocs.pm/ueberauth_shopify/api-reference.html) to ensure the public app is piped through an authenticated. 

Also, Instead of continually re-establishing a session, it might be an idea to have developers save their merchants `shop` and `access_token` to a database as per a discussion [here](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/best-way-to-store-shops-that-have-installed-my-app-and-their-token-448564). Hope this helps.

**Comment by Ninigi** [comment]
@panoply I started a [tutorial on how to build a shopify app using this package](https://medium.com/@fabian.zitter/elixir-shopify-apps-with-phoenix-d37e70afb1ea) but I still haven't finished part 2 😞

**Comment by panoply** [comment]
This is amazing. Thanks for putting your time into this. Can't wait to go over this when I have some time free up.
