### ISSUE TITLE
OAuth flow in test mock adapter seems incomplete

### ISSUE THREAD

**Issue by lewisf** [nsweeting/shopify#57]
https://github.com/nsweeting/shopify/blob/0769a02acb9d904af9d8af02d216e5abe7e69e14/lib/shopify/adapters/mock.ex#L92-L93

This function seems to just need to return {:passed, request} in order to continue. Otherwise `respond/1` fails, unable to handle `nil`.

Is there a reason this wasn't completed? Or maybe a future plan? Would love to help out with this if needed.

**Comment by Ninigi** [comment]
Yeah sorry for that 💩 We actually realized last week and I made a branch with a quick-fix, just so we could keep working, made a proper pull request now.
