### ISSUE TITLE
Shop name string treatment

### ISSUE THREAD

**Issue by overallduka** [nsweeting/shopify#6]
Well, this is an convenience and i think is really helpful, i lost some time trying figure out what was causing this:

`Shopify.session(shop) |> Shopify.OAuth.request_token(params["code"])` returning `{:error, 404..}`

My shop string (returned from shopify callback) was my-store.myshopify.com and this was the problem, so i do this:

`shop = String.replace(params["shop"], ".myshopify.com", "")` and to my surprise works fine and im receiving my `{:ok, ...access code and stuff}` now. Everything works fine.

**Comment by Ninigi** [comment]
This will happen automatically with the next version! :+1:
